In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(6,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

6

#### 2D Array

In [9]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape # (row, col)

(2, 3)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr1.size

6

#### 3D Array

In [14]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [15]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [16]:
arr3.ndim

3

In [17]:
arr3.shape

(3, 2, 3)

In [18]:
# (3, 2, 3)

In [19]:
arr3.size

18

### Create random array

In [20]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.906442  , 0.38602222, 0.12077114],
        [0.24510539, 0.52900831, 0.83588248]],

       [[0.55911641, 0.18653511, 0.32835252],
        [0.91316242, 0.9756706 , 0.68265697]],

       [[0.00448862, 0.02665535, 0.0421408 ],
        [0.5566636 , 0.5015717 , 0.18076851]]])

In [21]:
randomArr.dtype

dtype('float64')

In [22]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
zeroes.ndim

3

In [24]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [25]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [27]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [28]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [29]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [30]:
arr3[1][0][1]

np.int64(5)

In [31]:
arr3[1, 0, 1]

np.int64(5)

### Update & Delete

In [32]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [33]:
a1

array([[[0.90440936, 0.96060112],
        [0.52655447, 0.51335977],
        [0.82261498, 0.98568466]],

       [[0.31297053, 0.07302123],
        [0.18129774, 0.42290866],
        [0.25260063, 0.98841181]]])

In [34]:
a2

array([[[0.7386181 , 0.73341225],
        [0.25764159, 0.37795533],
        [0.98832745, 0.825881  ]],

       [[0.41404237, 0.85397057],
        [0.06800577, 0.89339518],
        [0.30597124, 0.01879252]]])

#### Basic Math Operarations

In [35]:
np.add(a1, a2)

array([[[1.64302746, 1.69401337],
        [0.78419606, 0.8913151 ],
        [1.81094243, 1.81156566]],

       [[0.7270129 , 0.9269918 ],
        [0.24930351, 1.31630384],
        [0.55857187, 1.00720433]]])

In [36]:
np.subtract(a1, a2)

array([[[ 0.16579126,  0.22718886],
        [ 0.26891288,  0.13540443],
        [-0.16571247,  0.15980366]],

       [[-0.10107184, -0.78094934],
        [ 0.11329196, -0.47048651],
        [-0.05337061,  0.96961929]]])

In [37]:
np.divide(a1, a2)

array([[[ 1.22446141,  1.30976966],
        [ 2.04374794,  1.35825512],
        [ 0.8323304 ,  1.19349478]],

       [[ 0.75589011,  0.0855079 ],
        [ 2.66591693,  0.47337245],
        [ 0.82556985, 52.59602448]]])

In [38]:
np.multiply(a1, a2)

array([[[0.66801312, 0.70451663],
        [0.13566233, 0.19402706],
        [0.81301297, 0.81405823]],

       [[0.12958306, 0.06235798],
        [0.01232929, 0.37782456],
        [0.07728853, 0.01857475]]])

#### Statistical operations

In [39]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [40]:
sqrt

np.float64(5.0)

In [41]:
abs

np.int64(2)

In [42]:
power

np.int64(256)

In [43]:
log

np.float64(3.2188758248682006)

In [44]:
mins

np.float64(0.07302123206801281)

In [45]:
maxs

np.float64(0.9883274516709427)

#### Update

In [46]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [47]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [48]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [49]:
# Reshape
arr3.shape

(3, 2, 3)

In [50]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [51]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [52]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
# Insert

In [56]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [59]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.69997644, 0.82384653, 0.17092449],
        [0.55490327, 0.77957952, 0.58256587]],

       [[0.941928  , 0.12354832, 0.15405042],
        [0.30784091, 0.00188112, 0.49246415]],

       [[0.6936978 , 0.46608544, 0.90651919],
        [0.39979597, 0.6100767 , 0.8939277 ]]])

In [60]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [61]:
arr5

array([[[0.55490327, 0.77957952, 0.58256587]],

       [[0.30784091, 0.00188112, 0.49246415]],

       [[0.39979597, 0.6100767 , 0.8939277 ]]])

In [62]:
np.save("new_array", arr5)

In [63]:
np.load("new_array.npy")

array([[[0.55490327, 0.77957952, 0.58256587]],

       [[0.30784091, 0.00188112, 0.49246415]],

       [[0.39979597, 0.6100767 , 0.8939277 ]]])